classification: three_d_printer
color: pla_aqua
description_extra: ''
description_main: reel
id: three_d_printer_filament_1_75_mm_pla_aqua_reel_3dqf
manufacturer: 3dqf
part_number: ''
size: 1_75_mm
type: filament
