classification: three_d_printer
color: ''
description_extra: ''
description_main: ''
id: three_d_printer_printer_wanhao_dupicator_i3_plus
manufacturer: wanhao
part_number: dupicator_i3_plus
size: ''
type: printer
