classification: three_d_printer
color: ''
description_extra: ''
description_main: minute
id: three_d_printer_printing_low_quality_minute
manufacturer: ''
part_number: ''
size: low_quality
type: printing
